exports.data = {
  zjEp4P1: {
    name: "Alex Ivkanov",
    bio:
      "I am an accidental software engineer, newbie dancer and amateur human",
    likes: "I love swimming, reading and hiking",
    location: "Berlin, Germany",
    profilePic: "https://m.imgur.com/zjEp4P1.png",
    friends: [
      "XK1e6X1.jpg",
      "qMYXVCn.jpg",
      "KhBHy5f.jpg",
      "EfLgPbT.jpg",
      "EaxJvLR.jpg",
      "XjX3OYr.jpg",
    ],
  },
  EfLgPbT: {
    name: "Tee Lilian",
    bio: "I read books. When I'm done, I read even more",
    likes: "I love reading, reading and reading",
    location: "Newyork, USA",
    profilePic: "https://i.imgur.com/EfLgPbT.jpg",
    friends: [
      "qMYXVCn.jpg",
      "KhBHy5f.jpg",
      "EaxJvLR.jpg",
      "XjX3OYr.jpg",
      "XK1e6X1.jpg",
      "zjEp4P1.jpg",
    ],
  },
  KhBHy5f: {
    name: "Jason Deelo",
    bio: "I live my best life every moment. What else can anyone do?",
    likes: "I love dancing, making music and reeling in more passive income",
    location: "London, UK",
    profilePic: "https://i.imgur.com/KhBHy5f.jpg",
    friends: [
      "XjX3OYr.jpg",
      "zjEp4P1.jpg",
      "EaxJvLR.jpg",
      "qMYXVCn.jpg",
      "XK1e6X1.jpg",
      "EfLgPbT.jpg",
    ],
  },
  qMYXVCn: {
    name: "Lee Ho",
    bio: "My friends call me the energy god. I never stop going",
    likes: "I love dancing, making music and reeling in more passive income",
    location: "Tokyo, Japan",
    profilePic: "https://i.imgur.com/qMYXVCn.jpg",
    friends: [
      "XK1e6X1.jpg",
      "EfLgPbT.jpg",
      "XjX3OYr.jpg",
      "zjEp4P1.jpg",
      "EaxJvLR.jpg",
      "KhBHy5f.jpg",
    ],
  },
  XjX3OYr: {
    name: "Cayo Caroline",
    bio: "Black, beautiful and strong",
    likes: "I love swimming, dancing and working out",
    location: "New Jersey, USA",
    profilePic: "https://i.imgur.com/XjX3OYr.jpg",
    friends: [
      "EfLgPbT.jpg",
      "XK1e6X1.jpg",
      "qMYXVCn.jpg",
      "EaxJvLR.jpg",
      "zjEp4P1.jpg",
      "KhBHy5f.jpg",
    ],
  },
  XK1e6X1: {
    name: "Tarzine Jacky",
    bio: "Life doesn't last forever. Cherising mine with smiles on my face",
    likes: "I love dancing, making music and reeling in more passive income",
    location: "Tokyo, Japan",
    profilePic: "https://i.imgur.com/XK1e6X1.jpg",
    friends: [
      "zjEp4P1.jpg",
      "qMYXVCn.jpg",
      "EfLgPbT.jpg",
      "KhBHy5f.jpg",
      "XjX3OYr.jpg",
      "EaxJvLR.jpg",
    ],
  },
  EaxJvLR: {
    name: "Dammy Ola",
    bio: "Living in the moment ...",
    likes: "I love hiking, travelling and skating",
    location: "Lagos, Nigeria",
    profilePic: "https://i.imgur.com/EaxJvLR.jpg",
    friends: [
      "XK1e6X1.jpg",
      "zjEp4P1.jpg",
      "qMYXVCn.jpg",
      "XjX3OYr.jpg",
      "EfLgPbT.jpg",
      "KhBHy5f.jpg",
    ],
  },
};
